### ISSUE TITLE
Unstable/unclear flow for CDTSharedManagedDocument context

### ISSUE THREAD

**Issue by rosslebeau** [IntrepidPursuits/code-review-luquant#7]
It looks like the CDTSharedManagedDocument is getting its context from the UIManagedDocument, which is creates asynchronously at init time. This means that the `context` property has no clear logic for when it will be available...creating the singleton `sharedManagedDocument` at app launch and hoping that it will have finished and created the context by the time other parts of the app need it is a pretty flawed approach. You need to either make the creation synchronous, provide some kind of callback, or implement a delegate/notification so that interested entities can know for sure when the context is created, and thus be able to use it. We can discuss an approach, but the main thing to learn here is that leaving things up to chance is never good for code, and waiting an arbitrary amount of time in the hope that an operation will complete is a bad asynchronous strategy, to say the least :)

**Comment by rosslebeau** [comment]
My bad, I missed the notification you had set up. Still need to implement it in the FlickrWebService - also take into consideration what happens if someone calls the FlickrWebService's methods and the context hasn't been created yet - do those calls just get forgotten and lost?

**Comment by luquantan** [comment]
Link to latest commit. Contains all fixes. Sorry.
7fa8b34fc5548b1fd5f191af2df34262f773d548

**Comment by luquantan** [comment]
Link to latest commit that fixes all issues.

luquantan/CoreDataTutorial@ 7fa8b34fc5548b1fd5f191af2df34262f773d548

**Comment by luquantan** [comment]
Link to latest commit that fixes all issues.

luquantan/CoreDataTutorial@7fa8b34fc5548b1fd5f191af2df34262f773d548
